install: |
  pdd -f /dev/null
  sudo bundle install --no-color "--gemfile=$(pwd)/Gemfile"
release:
  script: |-
    bundle exec rake
    rm -rf *.gem
    sed -i "s/0\.0\.0/${tag}/g" lib/jini/version.rb
    git add lib/jini/version.rb
    git commit -m "version set to ${tag}"
    gem build jini.gemspec
    chmod 0600 ../rubygems.yml
    gem push *.gem --key ${{ env.RUBYGEMS_API_KEY }}
merge:
  script: |-
    bundle exec rake
